import { Inter } from "next/font/google";
import { GeistSans } from "geist/font";
import { GeistMono } from "geist/font/mono";
import ClientProvider from "./components/ClientProvider";
import "./globals.css";

const geistSans = GeistSans();
const geistMono = GeistMono();
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${geistMono.className} ${inter.className} antialiased`}
      >
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
